### ISSUE TITLE
Consider switching to fast-jwt for performance

### ISSUE THREAD

**Issue by rmuchall** [krgamestudios/auth-server#6]
The dependency jsonwebtoken was deprecated by its author and the repository has been taken over by auth0. Although they've stated they have no plans to deprecate the library it appears to be in maintenance mode. Perhaps consider switching to fast-jwt which fastify is currently migrating to.

See:
https://github.com/nearform/fast-jwt
https://github.com/fastify/fastify-jwt/pull/184

**Comment by Ratstail91** [comment]
Are there any benefits besides performance?

**Comment by rmuchall** [comment]
Only that it appears to be more actively maintained (because it's a newer implementation).

**Comment by Ratstail91** [comment]
I see, thanks. This is a larger undertaking than it seems - the whole engine needs to be updated. Pretty much every server, and the front-end, uses the JWT in some way. 

So it's definitely something I want to do, just gonna take time.

**Comment by rmuchall** [comment]
No problem. It was just a suggestion. I just opened these issues because like you I've coded my own auth server and encountered these things during its development so thought I'd share :)
Best of luck with your game project!

**Comment by Ratstail91** [comment]
This is stale, closing.

It seems auth0 didn't end up deprecating this library, thankfully.
